image: python:3.9

before_script:
  - pip install selenium
  - wget -q https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - mv chromedriver /usr/local/bin/

stages:
  - test

test_selenium:
  stage: test
  script:
    - python test_connexion.py
